---
openapi: 3.0.0
info:
   version: 1.3.0
   title: clonetest162 open api specification
   description: production API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8007
     description: production
tags:
- name: production
paths:
   "/production":
      get:
         tags:
         -  production
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  production
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/production"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      production:
         type: object
         properties:
            material:
               type: "string"
               description: Description
            tools:
               type: "string"
               description: Description
            price:
               type: "number"
               description: Description
            quantity:
               type: "string"
               description: Description